# Generated by Django 4.2.5 on 2023-10-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingd', '0003_alter_appointmentd_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentd',
            name='service',
            field=models.CharField(choices=[('Urinary tract infection', 'Urinary tract infection'), ('Emergency Contraception', 'Emergency Contraception'), ('Skin conditions', 'Skin conditions'), ('Ear Health', 'Ear Health'), ('Sore throat test & treat', 'Sore throat test & treat'), ('Flu Vaccination', 'Flu Vaccination')], default='Doctor care', max_length=50),
        ),
    ]
