# Generated by Django 4.2.5 on 2023-10-02 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_prescription', models.CharField(blank=True, choices=[('Deliver prescriptions', (('Y', 'Yes, Prescription to be delivered'), ('N', 'No, Prescription not to be delivered')))], max_length=5, null=True)),
                ('default_pharmacy', models.CharField(blank=True, choices=[('Pharmacy', (('Beacons', 'Beacons Pharmacy'), ('Dowlais', 'Dowlais Pharmacy'), ('Georgetown', 'Georgetown Pharmacy'), ('Keir Hardie', 'Keir Hardie Pharmacy'), ('Lewis', 'Lewis Pharmacy')))], max_length=20, null=True)),
                ('default_ni', models.CharField(blank=True, max_length=20, null=True)),
                ('default_medicaln', models.CharField(blank=True, max_length=20, null=True)),
                ('default_gpsurgey', models.CharField(blank=True, max_length=20, null=True)),
                ('default_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('default_county', models.CharField(blank=True, max_length=80, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('default_email', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
