# Generated by Django 4.2.5 on 2023-10-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Urinary tract infection for women', 'Urinary tract infection for women'), ('Contraception', 'Contraception'), ('Skin conditions', 'Skin conditions'), ('Ear conditions', 'Ear conditions'), ('Sore throat test & treat', 'Sore throat test & treat')], default='', max_length=50),
        ),
    ]
