# Generated by Django 4.2.5 on 2023-10-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentb',
            name='service',
            field=models.CharField(choices=[('Urinary tract infection for women', 'Urinary tract infection for women'), ('Contraception', 'Contraception'), ('Skin conditions', 'Skin conditions'), ('Ear conditions', 'Ear conditions'), ('Sore throat test & treat', 'Sore throat test & treat')], default='Doctor care', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentb',
            name='time',
            field=models.CharField(choices=[('9 AM', '9 AM'), ('9:30 AM', '9:30 AM'), ('10 AM', '10 AM'), ('10:30 APM', '10:30 AM'), ('11 AM', '11 AM'), ('11:30 AM', '11:30 AM'), ('12 PM', '12 PM'), ('12:30 PM', '12:30 PM'), ('1 PM', '1 PM'), ('1:30 PM', '1:30 PM'), ('2 PM', '2 PM'), ('2:30 PM', '2:30 PM'), ('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM')], default='M', max_length=10),
        ),
    ]
